= Excel to Renpy
:toc: auto

== Introduction
This is a simple tool to convert an Excel file to a Renpy script. 
Each sheet in the Excel file will be converted to a Renpy label. The order of the sheets will be the order of the labels in the script.

There are 3 types of rows:

* Dialogue: This row represents a dialogue. The columns character, and text are required. The columns expression, and position are optional. If the character is not being showed it will be added before the dialogue.

* Menu: This row represents a menu. The column <<options, options>> is required.

* Scene: This row represents a scene. The column image is required. The column animation is optional.


[id=options]
== Options column

This column is used to define the options for a menu. The options are separated by the pipe(*|*) character. if the options include a jump to a label, the label and the option should be separated by *;* character. for example:

[,text]
----
text for option1;label1|option2;label2|option3;option4
----

== HIDE column
*Hide* column is an optional column that can be used in any row, this column could be empty or contain a list of characters separated by a pipe(*|*) character. This column is used to hide the characters in the list when the row is not empty.


== Example
This is an example of an Excel file in a `start` sheet:

// [cols="1,1,1,1,1,1,1,1,1",options="header"]
|===
|kind|character |text |expression |position| options| image| animation | hide

|dialogue| John |Hello! |happy |left | | | |
|dialogue| John |How are you? |happy |left | | | |
|menu| | | | |Option1;otherLabel\|Option2\|Option3 | |  |John 
|scene| | | | |image1 | | | 
|===

This is the Renpy script generated:
[,renpy]
----
define John = Character('John')

label start:
    show John happy at left
    "Hello!"
    "How are you?"
    hide john
    menu:
        "Option1":
            jump otherLabel
        "Option2":
        "Option3":
    scene image1
----